import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "../components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*<body className={inter.className}>{children}</body>*/}
      <main className="min-h-screen items-center justify-between p-24 grid grid-cols-4">
        <Sidebar />
        <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex col-span-3">
          {children}
        </div>
      </main>
    </html>
  );
}
